### ISSUE TITLE
The tray icon does not automatically switch the colour based on Windows Theme

### ISSUE THREAD

**Issue by Wikiwix** [xanderfrangos/twinkle-tray#109]
The tray icon is in principle adaptive to the system light or dark theme, but the colour is not **automatically** refreshed on a theme change, but only on a restart of Twinkle Try or clicking its tray icon.
Other apps like e.g. Viscosity or Docker Desktop do switch the colour automatically.

**Comment by Seo-Rii** [comment]
I think we can use nativeTheme.on('update'). I'm going to make a PR for this.

**Comment by xanderfrangos** [comment]
@Seo-Rii's PR has been merged and is now in v1.13.0. 👍

**Comment by tech189** [comment]
Still have this issue in v1.13.3, unfortunately. I have to click on the tray icon to get it to switch. EarTrumpet seems to switch by itself okay.

**Comment by xanderfrangos** [comment]
@tech189 Twinkle Tray relies on Electron to handle light/dark mode changes. It's possible that Electron is doing something wrong, or AutoDarkMode changes the Windows theme in a way that doesn't notify Electron. 

I've updated Electron in Twinkle Tray v1.13.4, in case there was a bug with Electron. Can you let me know if anything has improved for you?

**Comment by tech189** [comment]
Don't think it made any difference, sadly :(

**Comment by xanderfrangos** [comment]
@tech189 After some testing, it looks like the Windows Store version doesn't play as nice with AutoDarkMode. I assume this has something to do with Windows, since the code for the Windows Store and GitHub versions of the app are identical. If the theme changes are an issue for you, I'd recommend you use the [non-Windows Store version](https://github.com/xanderfrangos/twinkle-tray/releases/tag/v1.13.4).

**Comment by tech189** [comment]
Ah, that's sorted it thank you! (Great app btw!)
