### ISSUE TITLE
Turn off display feature not working.

### ISSUE THREAD

**Issue by Mahdi-Noor-Hasan** [xanderfrangos/twinkle-tray#135]
Model: ViewSonic VX2276-SHD

When I press the "turn off display" hotkey or click its tray pop-up icon, the screen display turns off for a second then automatically turns on. 
![Twinkle_Tray_QIWRecGpyL](https://user-images.githubusercontent.com/36124755/109523081-24deb880-7ad9-11eb-9069-894118a7d799.png)

**Comment by xanderfrangos** [comment]
The hotkey probably doesn't do what you think it does. It's the same as the "turn off after..." option in the Windows power settings. It just makes this activate immediately.

![Screenshot 2021-03-01 124247](https://user-images.githubusercontent.com/33106561/109536831-30f05900-7a8c-11eb-94d8-10070f50dead.jpg)

So any user input (mouse wiggle, keyboard press, controller input, etc.) will wake up the display(s). You're probably moving your mouse or it's detecting enough accidental movement to wake up the display(s).

**Comment by xanderfrangos** [comment]
As of v1.13.7, I've added a feature in the Hotkeys & Shortcuts menu that controls what the Turn Off Monitors feature does. The "Hardware signal" or "Hardware & software signal" option will work more like what you're looking for. However, the Hardware signal is not supported by all monitors and may not work. 

Since this new feature addresses your issue as best I can, I'm going to close this Issue. Feel free to open a new Issue if there's a problem, or leave feedback in the Discussions section.

**Comment by BlaisePx** [comment]
I know this has been marked as closed, but it comes up in google search when looking for answer to this exact problem of "screen display turns off for a second then automatically turns on". So I wanted to share the fix.

For me, it was using a displayport cable with my Acer EI322QUR monitor, rather than an HDMI cable. With displayport, the monitor turns off and then on in a second and it is **not** because mouse is being moved or some other input that would wake the monitor. Changed to HDMI and the turn off monitor feature works perfectly.
