### ISSUE TITLE
[Feature request] Hotkey support

### ISSUE THREAD

**Issue by jordi-7** [xanderfrangos/twinkle-tray#2]
Been using the app for a while and I love it, but I think that support for custom hotkeys would be a great addition.
Keep up the good work!

**Comment by xanderfrangos** [comment]
Thanks for the suggestion! This is the next feature on my to-do list. I'm planning to have hotkeys for increasing/decreasing brightness of all displays and individual displays. Are there any other hotkeys that you think should be included?

**Comment by jordi-7** [comment]
Managing brightess would be enough for me, maybe also turning the displays on/off. I'll leave the rest up to your imagination.
Thanks!

**Comment by jordi-7** [comment]
Hi,
I've thought of something I'd like to propose. There could be hotkeys to manage brightness in two ways. First, increasing and decreasing brightness by a configurable amount, as you previously said. But I'd appreciate if I could also activate a preset with a hotkey, just like Time of Day Adjustments does, but manually.

**Comment by xanderfrangos** [comment]
[v1.8.0 has been released](https://github.com/xanderfrangos/twinkle-tray/releases) with basic hotkey support. Setting up hotkeys can be a little finicky, but that's generally due to existing global hotkeys from Windows and other apps.

Hotkeys for brightness presets is a good idea. I'll add that one to my to-do list.

In the meantime, let me know if you run in to any issues with the hotkeys or have any other thoughts.

**Comment by jordi-7** [comment]
I've been playing around a little bit with it and works fine. I'll continue using it daily and I'll let you know if I have any issues. Thanks
