### ISSUE TITLE
Triggered UPerfect portable display panel to die/go black

### ISSUE THREAD

**Issue by birnsi** [xanderfrangos/twinkle-tray#265]
I just encountered a very off issue when using Twinkle Tray with my portable display (Uperfect 4K Portable Monitor M156A07) and Windows 11.
I installed from the Microsoft Store, tried to adjust the brightness slider, and my display went dark, then came back on. I Tried again and the display went dark again, but now permanently. I've reached out to the manufacturer to see what could be up, but right now it appears that the panel is either dead or stuck off. I ruled out a video card issue as my video car is working with other displays. I also tried the monitor with other devices and it definitely appears to be dead. However, windows does still recognize the display when connected and the power light on the display indicated that it's working. It just appears that the panel won't turn on. 
I seems hard for me to believe that Twinkle Tray could possibly kill a panel so I suspect some sort of hardware issue with the panel itself, somehow... triggered by Twinkle Tray... even though I've had no issues with the display in the 5 months I've owned it.

I thought I should mention this here just in case anyone else ever encounters something similar. 
But I'm totally at a loss as to what could have happened.

More details here:
https://linustechtips.com/topic/1389078-did-twinkle-tray-kill-my-monitor/

**Comment by xanderfrangos** [comment]
Hey @birnsi,

Sorry to hear about the monitor. I can't see a reason why Twinkle Tray would fry anything. Twinkle Tray only sends DDC/CI messages to the display, which the manufacturer has to explicitly enable on their end in the first place. So the app isn't forcing the display to do anything it shouldn't. Additionally, Twinkle Tray only sends DDC/CI messages a few times per second (unless you set the speed to "Ludicrous") to avoid any issues. For example, I have a Dell U2415 that will flicker and lag behind on updating the brightness if updated too quickly. This is actually why the brightness updates aren't "smooth", as Anthony mentioned in his LTT video mentioning Twinkle Tray.

That said, I would recommend downloading ControlMyMonitor (https://www.nirsoft.net/utils/control_my_monitor.html) to see if there are any other "Brightness" values that you can adjust to turn the display back on. ControlMyMonitor is a great tool for discovering all of the DDC/CI features available on your display and playing with the values. Some manufacturers will enable DDC/CI for use with their first-party software (ex. Dell, LG), but then use the DDC/CI standard in a non-standard way. For example, I've heard of displays having a "minimum" brightness DDC/CI value of 50, even though the standard always starts at 0. It's possible that your portable display does something similar and simply turned off the screen due to how it handles certain values. That's just a wild guess, since I'm not familiar with the monitor.

If that doesn't help, I hope you can get it resolved with the manufacturer!

**Comment by birnsi** [comment]
Thanks for the reply Xander! And thanks for all the extra information. It seemed extremely unlikely to me that Twinkle Tray would have any ability to mess up the monitor itself, so I'll try out your suggestions and if all else fails I'm talking with the manufacturer to get it worked out. 
A super strange occurrence in any case. I'll update if any of your suggestions work.

Thanks again!

**Comment by birnsi** [comment]
It worked! I downloaded ControlMyMonitor and used it to reset the monitor settings to factory default and the panel came back on.
Thanks for the suggestion! I didn't catch which monitor setting was causing the issue, but in any case setting back to factory default with ControlMyMonitor solved it, haha. 
Good to know in case anyone else ever encounters the same issue.
