### ISSUE TITLE
[Feature Request] Key-binds for specific brightness

### ISSUE THREAD

**Issue by WiBla** [xanderfrangos/twinkle-tray#324]
Hello,

I'm building a macro pad, and I was thinking that I could add a photo-resistor to it, that way it could somehow change the brightness of my monitors automagically based on the room's light level, exactly like what most smartphones do.

In order to achieve this, it would be super useful if the app allowed for individual shortcuts per brightness level, say something like:
- [ALT] [SHIFT] [1] for 10%
- [ALT] [SHIFT] [5] for 50%
- [ALT] [SHIFT] [9] for 90%

I might even go further; if there was an API of sorts, that the macro pad could communicate with, that would be even better, but I have no clue how feasible this is for you.

This is somewhat related to #295.

**Comment by xanderfrangos** [comment]
Hi @WiBla,

Neat!

I think the best option would be to use [the Command Line options](https://github.com/xanderfrangos/twinkle-tray#command-line-arguments). If you adjust the "Normalize Brightness" settings for each display so that their min/max values match what you want in the darkest/brightest ambient light, you could then use the `--All` flag and `--Set` to adjust all displays to whatever formula you come up with for the the measured ambient light.

A full command would probably look like:
`"%LocalAppData%\Programs\twinkle-tray\Twinkle Tray.exe" --All --Set=55`

FYI, this requires you to not use the Windows Store version of Twinkle Tray.

**Comment by WiBla** [comment]
Thanks for the quick reply!

This helps very much, I now just need to figure out how to call the .exe using the arduino 😃

I'll tinker with it and report my findings here for future reference 👍

**Comment by WiBla** [comment]
I can happily report that this sketch works for me :

```cpp
#define HID_CUSTOM_LAYOUT;
#define LAYOUT_FRENCH // Make sure to define your layout here
#include <HID-Project.h>

// Photoresistor
const int LDR = A10;
int sensorValue = 0;

// Debug button, no keyboard inputs are sent unless the button is pressed
const int BTN = 16;

void setup() {
  Serial.begin(115200);
  Keyboard.begin();
  pinMode(BTN, INPUT);
}

void loop() {
  sensorValue = map(analogRead(LDR), 0, 1023, 0, 100);
  Serial.println(sensorValue);
  delay(2000);

  if (digitalRead(BTN) == HIGH) {
    Keyboard.press(KEY_LEFT_GUI);
    Keyboard.write('r');
    Keyboard.releaseAll();
    delay(100);
    Keyboard.println("cmd");
    delay(250);
    Keyboard.print("\"%LocalAppData%\\Programs\\twinkle-tray\\Twinkle Tray.exe\" --All --Set=");
    Keyboard.println(sensorValue);
    delay(100);
    // Close the cmd prompt
    Keyboard.press(KEY_LEFT_ALT);
    Keyboard.press(KEY_F4);
    Keyboard.releaseAll();
  }
}
```

Simple, but effective! Thanks again for your quick help.
