### ISSUE TITLE
GPU usage spike on a specific location of the screen when Twinkle Tray is running

### ISSUE THREAD

**Issue by AriesLaCroix** [xanderfrangos/twinkle-tray#372]
I'm getting a very weird issue with this app. When Twinkle Tray is running, once my mouse hovers in the upper left side on my GPU usage increase from 1-2% (idle) to around 20%. The only fix is either I close/restart the app or restart my PC a couple of times until I don't see any GPU usage when I hover and move the mouse on the upper left side of my screen. It also affects my games , lowering my FPS, and again, when my mouse hovers to the upper left side of my screen. I already tried re-installing my GPU drivers (AMD Radeon 6700XT) but still the issue persist. 

Any help is appreciated, thanks!

**Comment by xanderfrangos** [comment]
@FranMCodes Under certain conditions, Twinkle Tray would unintentionally display an invisible window in the top left of the screen (usually at startup before opening the flyout or using hotkeys). That was fixed in v1.14.4. It's possible this was causing @AriesLaCroix's reported GPU spikes. Or maybe not. Either way, the issue should be resolved in recent versions.

**Comment by xanderfrangos** [comment]
Closing this, as the bug was resolved a while ago. 👍
