### ISSUE TITLE
Performance issue with version 1.14.0 and up

### ISSUE THREAD

**Issue by LivioZ** [xanderfrangos/twinkle-tray#410]
Hello, with those versions of Twinkle Tray I have a big lag of my mouse (and quite possibly the entire PC) when I for example open up Google Chrome or do some heavy tasks. This doesn't happen with versions below 1.13.11. I am sure it is TT because if I uninstall it the issue disappears and if I reinstall it it happens again, tried from a fresh Windows 10 installation.

Specs:
Intel i5 4590
8GB RAM
GTX 970

EDIT: realized it happens when CPU goes to 100%

**Comment by tongfeima** [comment]
Hi, I meet the same problem as yours. but I tried 1.10~1.13, the mouse lag will happen but not obviously.
When I quit the Twinkle Tray, this problem will disappear.
Hope they can help us to solve it.

**Comment by Loris19** [comment]
I noticed the same issue since the last update. Took me a while to realize it was Twinkle Tray, but as you mention quitting it gets rid of mouse cursor slowdowns

**Comment by xanderfrangos** [comment]
Hi guys,

There have been similarly reported issues as of late, [here](https://github.com/xanderfrangos/twinkle-tray/issues/406) and [here](https://github.com/xanderfrangos/twinkle-tray/issues/415). I've been working on (unreleased) adjustments to the mouse tracking code to help as much as I possibly can. When you disable the "Tray icon scroll shortcut", the mouse is no longer tracked while the flyout/overlay is closed.

![scroll-shortcut](https://user-images.githubusercontent.com/33106561/184554573-7798d067-fb3e-4f4b-8159-37c3d4e43571.png)


Additionally, I've added a dev toggle to fully disable the mouse tracking entirely. However, it probably won't do anything else to help.

![Screenshot 2022-08-14 160644](https://user-images.githubusercontent.com/33106561/184554580-04b0f427-5f08-47b6-9f17-8dffa3bbc349.png)


All of that said, Electron (or Chromium) ALSO has a global mouse event hook. It is running almost constantly. This means that nearly ALL Electron apps will eat up a tiny amount of CPU usage when moving your mouse, depending on your polling rate. [(See examples) ](https://user-images.githubusercontent.com/33106561/184554591-4406a9c9-f4f7-47d9-9ff5-f4797310dc86.jpg)


I'll open an issue with Electron so that they hopefully look into it. In the meantime, below are two preview builds of Twinkle Tray v1.14.5. One is using the latest version of Electron (20) and the other uses the older Electron 13, which was used in Twinkle Tray v1.13.11. Please let me know if either of these (or both) help mitigate the mouse issues.

v1.14.5-electron13: https://1drv.ms/u/s!AiWKFpjcSKRQhtgdwf3NuQ6dFDAP6A?e=KJclSI
v1.14.5-electron20: https://1drv.ms/u/s!AiWKFpjcSKRQhtgep7EJbpZLKJKR2Q?e=QvEubb

Thanks!

**Comment by Loris19** [comment]
Hi, thanks for the answer ! I just tried both preview builds, but unfortunately neither of them mitigated or fixed the issue for me. Disabling the Tray icon scroll shortcut also didn't help. However, disabling mouse events via the debug menu did the trick.

If that can help, I'm on Windows 10 21H2 with an i5 7600K.

**Comment by xanderfrangos** [comment]
Hi all,

I think I've finally got the mouse CPU down to 0%. I found a way around the Electron bug and improved when my mouse tracking code. There's a new build (v1.14.5-beta2) available here:
https://1drv.ms/u/s!AiWKFpjcSKRQhtgircOPtXK1VvnHMQ?e=RncyE5

Turning off features should not be required any more.

Let me know if this build helps.

Thanks!

**Comment by LivioZ** [comment]
Works really well, no issue. Thank you very much!

**Comment by xanderfrangos** [comment]
@LivioZ Great! Thanks for confirming. 

I realized that I bumped the version number too far. The next version is actually v1.14.4. That update should drop soon with additional (unrelated) fixes.

**Comment by xanderfrangos** [comment]
This issue has been resolved as of v1.14.4. 👍
