### ISSUE TITLE
Power off DDC/CI hardware signal not working in v1.14.7

### ISSUE THREAD

**Issue by McBaws** [xanderfrangos/twinkle-tray#455]
In v1.14.5, the power off button and shortcuts in the app work, yet in v1.14.7, the power off button and shortcuts stopped working.
The Turn Off Displays action is set to hardware signal only.
Were there any changes made between these versions that stopped the power off button and shortcuts from working properly?

Another strange fact is that in v1.14.5 VCP codes in CLI didn't work, yet in v1.14.7 they do.

**Comment by Laitauxnards** [comment]
Same thing constated for me and it worked correctly before

**Comment by xanderfrangos** [comment]
If you're not using the Microsoft Store version (meaning the version from twinkletray.com or GitHub), try this beta version and let me know if it helps:
https://1drv.ms/u/s!AiWKFpjcSKRQhtg9FAqPqY3r91G0tg?e=uzrQd0

**Comment by Laitauxnards** [comment]
I tried the test version you provided and its still not working. I can confirm my monitors turn off with others app I tried and in the debug menu the monitors turns off when I set the turn off signal to 4, the problem is 1) its not saving this config and 2) its still not working even I think this would solve the problem. 
It worked correctly in previous version of your software

**Comment by McBaws** [comment]
Issue was fixed multiple versions ago, closing this now.
