### ISSUE TITLE
[Feature Request] Hide slider UI and background program keyboard shortcut adjustment function

### ISSUE THREAD

**Issue by Kony-lib** [xanderfrangos/twinkle-tray#498]
Currently, I use ESP32 C3 and photosensitive sensor for ambient light capture, and use keyboard shortcuts with twinkle-tray to control screen brightness. However, when using the keyboard shortcut to adjust the brightness, the slider UI always interrupts and obscures the software being used.
Is it possible to add a function that can use keyboard shortcuts for background brightness adjustment and the top level does not show the slider UI?
![image](https://user-images.githubusercontent.com/62421664/203939289-c38f35ca-6a75-48fc-92db-c9a75640fa31.png)
![IMG_20221125_163415](https://user-images.githubusercontent.com/62421664/203939450-c3f447e3-cba6-427d-af91-6f4d9bbc1b8f.jpg)

**Comment by xanderfrangos** [comment]
Disable overlay will do what you're looking for 👍

![Screenshot 2022-11-25 105606](https://user-images.githubusercontent.com/33106561/204020625-608f28e9-dbb8-4618-a315-89d1f566d8fd.png)

Also, you can use [the CLI](![image](https://user-images.githubusercontent.com/33106561/204020815-225e593a-0963-4b7b-8f06-ca3c532b2236.png)) instead of keyboard shortcuts. It doesn't trigger the overlay by default.

**Comment by Kony-lib** [comment]
Thank you so much for your help!
