### ISSUE TITLE
Pre-releases and update channel promotion

### ISSUE THREAD

**Issue by brogers5** [xanderfrangos/twinkle-tray#610]
Hey @xanderfrangos, had a question regarding Twinkle Tray's release process as it relates to the Chocolatey package.

I've noticed the last couple Stable releases had an initial rollout as a "pre-release" in GitHub. Both Twinkle Tray's update checker and the script I've set up for updating the Chocolatey package key off this to help determine the latest version for the Beta update channel.

In the previous release's case, this threw me off, as I noticed its version string lacked the SemVer string suffix (i.e. `-beta`) used in previous Beta versions. Chocolatey requires this to distinguish between a stable and pre-release package version, and I'd prefer for Chocolatey's upgrade command to respect the user's update channel preference. The release's pre-release flag stuck around for long enough that I had moved forward with padding the package's version accordingly, only to later find it was promoted to the Stable channel after the package went live. This necessitated me having to rebuild and push another package with the intended version.

Going forward, I'd like to avoid some of the problems that could come from this (e.g. building and publishing effective duplicate package versions for a given release, unlisting erroneously published package versions, needing to publish package fix versions, etc.). Notably, a given package version on Chocolatey's Community Repository will become immutable once it passes the moderation process. The Twinkle Tray package has since worked its way toward becoming a "trusted package" and is no longer subject to human moderation, so if a new package version gets pushed, I have a limited window of time to intercept it or make corrections before it goes live.

Is it safe to assume a given release without a string suffix will eventually be promoted to the Stable channel? If so, should the script be ignoring "pre-releases" that meet this criteria for the Beta channel? If not, at what point should we consider a given release's channel assignment to be immutable?

**Comment by xanderfrangos** [comment]
So the way I have Twinkle Tray wired up, the "beta" update channel in Twinkle Tray will pull whatever is the latest release on GitHub (including those tagged as pre-release), where as the "stable" channel excludes anything with the pre-release tag. 

I have the "beta" channel so that I can roll out in-progress updates under the pre-release tag and a `-beta` suffix (i.e. `v1.16.0-beta1`). However, I haven't had much time for developing lately, so I haven't used any `-beta` suffixes. 

For the last few updates, I've been using the pre-release tag to confirm that there are no glaring issues that I somehow missed. Only a small pool of people use the "beta" branch or watch the project close enough to notice those releases. Once I see that a handful of people are using it without issue, I've been removing the pre-release tag and tagging it as the latest release.  

So yeah, a release without a suffix should eventually be promoted to the "stable" channel. But to be safe, I would only consider a release immutable and ready for the "stable" channel when it doesn't have a pre-release tag. Anything with a pre-release tag I would consider to be "beta", whether or not it has a suffix.

**Comment by brogers5** [comment]
Gotcha, thanks for confirming. I'll proceed with ignoring such releases until they're promoted.
