### ISSUE TITLE
Fn Keys not detected on hotkeys config

### ISSUE THREAD

**Issue by mschief148** [xanderfrangos/twinkle-tray#85]
As the title says the fn keys are not detected on hotkeys config

**Comment by xanderfrangos** [comment]
I'm assuming you're talking about the `Fn` key specifically, not the `F1`-`F12` keys? The `Fn` key is handled by the keyboard itself, not Windows. Because of this, the only way to use the `Fn` key with Twinkle Tray is if your keyboard has its own software that can assign keys to key combos. For example, you bind the combo `Fn + F4` to the `F13` key. If your keyboard doesn't support that, there isn't a way to detect those key combos.

**Comment by mschief148** [comment]
Oh, I see. Thanks for the answer it's clear now.
