### ISSUE TITLE
Why need four processes?

### ISSUE THREAD

**Issue by jay52121** [xanderfrangos/twinkle-tray#96]
Best app in win10!
but i want know is 1XX MB in win10 store？some other app just need 1.X MB.
And why need four processes?
Thanks to xanderfrangos!

**Comment by xanderfrangos** [comment]
Hi @jay52121. I'm glad you like the app. 😀

Twinkle Tray was made using [Electron](https://electronjs.org), which uses a small web browser (Chromium) to display the GUI. Using Electron has been the only way I could reasonably make/manage the app in my limited free time. Because Electron is essentially a web browser, it also has to include more files and use a bit more RAM than a similar C++/C# app. I don't think it's a problem, as Twinkle Tray typically uses no more than 80MB of RAM (<1% on a 8GB PC) and ~0% CPU when idle. 

Here are what each of the 4 processes are:
1. The main NodeJS process for communication with monitors and handling settings.
2. A process for network communications. (Electron needs this on a 2nd process for some reason.)
3. A process for the brightness panel GUI/logic.
4. A process for communicating with the GPU (for transparency effects). 

I hope that clears things up.

**Comment by LakeishaKowalczyk** [comment]
@xanderfrangos 
love you

**Comment by avisek** [comment]
@xanderfrangos, I want to express my gratitude for creating such an incredible app. I believe it would be absolutely perfect if it were developed using native C++/C#. Looking forward to an update with that implementation ;-)

**Comment by xanderfrangos** [comment]
> @xanderfrangos, I want to express my gratitude for creating such an incredible app. I believe it would be absolutely perfect if it were developed using native C++/C#. Looking forward to an update with that implementation ;-)

@avisek Much appreciated. I have no plans to rewrite Twinkle Tray in C# ever. There are other app that are C# based, such as the excellent Monitorian. There definitely won't be a C++ version, as the only C++ I've written is for a few Node modules that Twinkle Tray references. I'm surprised those even work. 😅

**Comment by Robot1me** [comment]
> Much appreciated. I have no plans to rewrite Twinkle Tray in C# ever.

Definitely understandable. However if you find the time and interest, please add a way to optionally disable the GPU render process, to fallback on software rendering. Because the GPU process is the biggest elephant in the room and it would probably be the easiest option to implement. Screenshot of the memory usage:

![Image](https://github.com/user-attachments/assets/04754fc7-8dbc-43da-9804-820664dc4355)
